source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'

gem 'activeresource'

group :development do
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'guard-rspec', require: false
end

group :development, :test do
  gem 'rspec-rails'
end

group :test do
  gem 'simplecov', require: false
  gem 'capybara'
end
