default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: burguer-api_development

test:
  <<: *default
  database: burguer-api_test

production:
  <<: *default
  database: burguer-api_production
  username: burguer-api
  password: <%= ENV['burguer-API_DATABASE_PASSWORD'] %>
