source 'https://rubygems.org'

gem 'rails-api'
gem 'pg'

group :development do
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'guard-rspec', require: false
  gem 'annotate', ">=2.6.0"
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :test do
  gem 'simplecov', :require => false
  gem 'database_cleaner'
end
